### ISSUE TITLE
Leaving queue instead of accept invitation

### ISSUE THREAD

**Issue by Xoshy** [tg123/BattleInfo#13]
Very useful addon.
But for already a week or maybe even more there's about 20% chance that [start battle] button will make you leave queue instead of accept invitation.
And it becomes rather severe when you get your AV queue cancelled after 1h+ of waiting.
How can we fix tit?

**Comment by tg123** [comment]
uncheck 'Replace Enter Battle Button with count down'

this might happen if you are in combat and battle info cannot find correct button due to blz restrictions
