### ISSUE TITLE
If you delete Battle info addon, the default display will not appear on the battlefield.

### ISSUE THREAD

**Issue by CDragon03** [tg123/BattleInfo#3]
If you delete Battle info addon, the default display will not appear on the battlefield.

I don't know what I should do.

**Comment by tg123** [comment]
warsong gulch or alterac?
the alterac one is created by battleinfo

**Comment by CDragon03** [comment]
Can I delete add-on and leave the basic battlefields behind?

**Comment by tg123** [comment]
To make it more clear

for 
![image](https://user-images.githubusercontent.com/170430/71426733-fa86a500-2662-11ea-9e13-505c023ab85c.png)
you cannot, this is created by Battleinfo

for 
![image](https://user-images.githubusercontent.com/170430/71426734-05d9d080-2663-11ea-9bd2-ae4b45a72a37.png)
you can, it is an ORGANIC blizzard bar.

**Comment by CDragon03** [comment]
애드온을 삭제하면 아래 이미지가 보이지 않는다.


> 당신을 위해 , 그것은 유기 블리자드 바입니다.
> ![영상](https://user-images.githubusercontent.com/170430/71426734-05d9d080-2663-11ea-9bd2-ae4b45a72a37.png)

**Comment by tg123** [comment]
Battleinfo will NOT change warsong scorebar.

if you moved scorebar and want to reset it, do below in game chatbox, 
type
`/script UIWidgetTopCenterContainerFrame:SetUserPlaced(false)`
and restart your game

**Comment by CDragon03** [comment]
If we delete the add-on, we don't have any information on the Altrek battlefield.

**Comment by tg123** [comment]
There is NO default score bar for Alterac
Thus, no addon no score bar

**Comment by CDragon03** [comment]
This means that if battle info add-on is deleted, existing basic battlefield information will be lost.

**Comment by tg123** [comment]
Correct, No score bar for Alterac
