### ISSUE TITLE
Elapsed time seems to bug out

### ISSUE THREAD

**Issue by Finrodi** [tg123/BattleInfo#7]
The elapsed time seems to be bugged and disappear very often. I do not get any lua error tho. Not sure how that helps.

On a side note, would be nice to see to be able to see the name of the flag carriers next to the score.

**Comment by tg123** [comment]
could you please show me a screenshot

or first disable all other addons and try again to confirm there is no conflict

**Comment by tg123** [comment]
Reopen if you still have issue
