### ISSUE TITLE
作者你好！非常喜欢你的插件！

### ISSUE THREAD

**Issue by tzn521** [tg123/BattleInfo#8]
作者你好！非常喜欢你的插件！
问个问题。既然可以自动出战场，那请问能否增加 自动进入战场功能。虽然有点偷懒嫌疑，但是有时候真的会很方便。比如可以自己调整倒计时60秒自动进入。非常感谢！
Hello, author! I love your plugins!
Ask a question. Since it can automatically go out of the battlefield, can you add the function of automatically entering the battlefield. It's a little lazy, but sometimes it's really convenient. For example, you can adjust the countdown to 60 seconds to enter automatically. Thank you very much.

**Comment by tg123** [comment]
Blizzard 禁止这类 API 所以无法实现
此功能仅存在于BattleInfo 在60年代的版本 (非怀旧服)
