### ISSUE TITLE
Classic Time Elapsed Vanished?

### ISSUE THREAD

**Issue by Havenloft** [tg123/BattleInfo#9]
Something seems to have changed since the last update. I can no longer see the Battleground time elapsed? Is this a Blizzard change or was it the addon? Seemed to be working fine just recently.

**Comment by tg123** [comment]
![image](https://user-images.githubusercontent.com/170430/76613729-f50b5f00-64db-11ea-9f7a-72833c3efb2b.png)

which timer?
nothing changed and works fine on my test, could you please point it out?

**Comment by ghost** [comment]
That happens a few times a week for me aswell, while the rest of the addon UI seems to work without issues.

I'll try run this the next time to see if it's an addon or Blizzard issue:
/script print(GetBattlefieldInstanceRunTime())

**Comment by ghost** [comment]
Time Elapsed suddenly stopped working around 1 AM night to wednesday. GetBattlefieldInstanceRunTime() returns "0". Stays zero for all battlegrounds since then.

Reloading UI didn't help.
Restarting game did not help.

**Comment by tg123** [comment]
could you please disable all other addons?
works fine here

**Comment by ghost** [comment]
EU server btw. Server restart didn't fix it.

Disabling absolutely all addons didn't help.

This is typical:
![GetBattlefieldInstanceRunTime()](https://user-images.githubusercontent.com/32784121/76972490-f18a3480-692e-11ea-940d-8eb3105e5935.png)
If it stops working it's usually 1-3 mins into a BG or so. In this case it's somewhere around 2min 45s.

**Comment by ghost** [comment]
In other cases it never works after logging into the game.

**Comment by ghost** [comment]
After these tests I just stopped changing anything. Just let the function return 0, and ye, it stayed like that in the following WSG's. Then after being AFK in Orgrimmar for 15 mins the AV queue pops, and now it suddenly shows normal values again. Even tried to spam the script to see if it's sensitive to that, but no.

/shrug

**Comment by tg123** [comment]
i do not think it has something to do with AFK.

could you please take a look at scoreboard?
there should be a time elapsed at the bottom of the board.

**Comment by ghost** [comment]
Those times I've checked because it missed from the addon it also missed there.

**Comment by tg123** [comment]
seems that is blz bug. You may want to report it to blizzard :(

**Comment by Havenloft** [comment]
I'll let you know if it becomes an issue again but this appears to be fixed in AV at least. Not sure if timers ever existed in WSG or AB? If they did then they do not work currently.

**Comment by tg123** [comment]
Confirmed
it is a server side issue :(
